export: Command not found.
export: Command not found.
export: Command not found.
export: Command not found.
Badly placed ()'s.
 
Running threaded PSI4 on node17 
/home/mdavis/anaconda3/envs/p4env/bin/psi4
 
Working and scratch directories
/home/mdavis/f12eom_optimizer/tests/slurm
/scratch/mdavis/PSI4_2022-08-17_15:47:40.504364532
 
use -n:  to specify number of threads
use -i:  to specify input  file     (default = input.dat)
use -o:  to specify output file     (default = file.out )
 
-h or --help for more options
 
Running...
Traceback (most recent call last):
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 237, in <module>
    main()
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 199, in main
    psi_gradient, psi_energy = real_run_psi4(molsys_obj)
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 99, in real_run_psi4
    psi4.set_options({'reference': 'rohf', 
  File "/home/mdavis/anaconda3/envs/p4env/lib/python3.10/site-packages/psi4/driver/p4util/python_helpers.py", line 473, in set_options
    raise ValidationError(f'Error setting options: {rejected}')
psi4.driver.p4util.exceptions.ValidationError: Error setting options: {'charge': ('0', RuntimeError('\nFatal Error: CHARGE is not a valid option.\nError occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/liboptions/liboptions.h on line: 55\nThe most recent 5 function calls were:\n\npsi::Options::use(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)\n')), 'spin': ('0', RuntimeError('\nFatal Error: SPIN is not a valid option.\nError occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/liboptions/liboptions.h on line: 55\nThe most recent 5 function calls were:\n\npsi::Options::use(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)\n'))}
...Done
 
